theme = "catppuccin_mocha"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = false

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"
