[language-server.csharp-ls]
command = "csharp-ls"

[[language]]
auto-format = true
name = "c-sharp"
scope = "source.cs"
file-types = ["cs"]
roots = [".sln", ".csproj"]
language-servers = ["csharp-ls"]
